title: Abdullah Al-Nafisah
email: abdullah.y.alnafisah@gmail.com
description: >-
  Personal website and blog of Abdullah Al-Nafisah — Electrical Engineer, Researcher, Developer.
baseurl: ""
url: "https://abdullahalnafisah.github.io"
theme: minima
minima:
  skin: dark
markdown: kramdown
